name: Deepak Pipeline
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
    
jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from dev branch
    - name: checkout code
      uses: actions/checkout@v5.0.0

    - name: nodejs steup
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: install dependies
      run: npm install

    - name: runtest
    - run: |
        mkdir -p test results
        npm test -- --reporter mocha-junit-reporter--reporter-options mochaFile=./test-results/results.xml
   
 
